module.exports.ad = {
    trumpman:[
        'katerinaramm',
        'palikari123',
        'lordneroo',
        'cryptomaniacsgr',
        'nikoleondas',
        'knowhow92'
    ],
    kiokizz:[
        'dagger212'
    ],
    ecoinstant:[
        'chuckrick',
        'music4peace',
        'pfunk',
        'dswigle',
        'vimukthi',
        'amphlux',
        'allcapsonezero',
        'jfang003',
        'sicarius',
        'mineopoly',
        'kevinnag58',
        'lxsxl'
     ] ,
    'd-zero': [
        'autobodhi'
    ],
    'kenny-crane':[
        'sergey44',
        'reeta0119',
        'nataly2317'
    ],
    failingforwards:[
        'definethedollar'
    ],
    'no-advice':[
        'an-man',
        'crrdlx',
        'spinvest-leo',
        'hellene8'
    ],
    hivediver:[
        'feuerelfe'
    ],
    bozz:[
        'galberto'
    ],
    minimining:[
        'instagram-models',
        'mimismartypants'
    ],
    preludiocosmico:[
        'javiersebastian'
    ],
    novacadian:[
        'omitaylor'
    ]
}